// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Models;

namespace Movies.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    partial class MovieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Movies.Models.MovieFormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Category = "Family",
                            Director = "Nathan Greno & Byron Howard",
                            Edited = false,
                            LentTo = "",
                            Notes = "The best movie to ever exist.",
                            Rating = "PG",
                            Title = "Tangled",
                            Year = 2010
                        },
                        new
                        {
                            FormId = 2,
                            Category = "Family",
                            Director = "Michael Gracey",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Greatest Showman",
                            Year = 2017
                        },
                        new
                        {
                            FormId = 3,
                            Category = "Action/Adventure",
                            Director = "Taika Waititi",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Thor: Ragnarok",
                            Year = 2017
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
